{{ if not .Values.config.configmapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "tsung.configmap" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "tsung.fullname" . }}
data:
{{ (tpl (.Files.Glob (tpl `{{ .Values.config.configfolderglob }}` . ) ).AsConfig .) | indent 2 }}
{{ end }}
