---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "tsung.slave" . }}
  labels:
    app: {{ template "tsung.fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: slave
spec:
  serviceName: {{ template "tsung.slave-svc" . }}
  replicas: {{ .Values.slave.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "tsung.fullname" . }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: slave
    spec:
      containers:
      - name: tsung
        image: ddragosd/tsung-docker:1.6.0
        env:
        - name: SLAVE
          value: "true"
      terminationGracePeriodSeconds: 2

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "tsung.fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: slave
  name: {{ template "tsung.slave-svc" . }}
spec:
  clusterIP: None
  selector:
    app: {{ template "tsung.fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: slave
  ports:
  - port: 22
    name: ssh
  type: ClusterIP
---
